# Site settings
title: Semester 6 
description: "My Academic Work. Most of it anyway."
url: ""
ogimage: "img/default-ogimage.png"
author:
  name: "Zubair Abid"


# Build settings
baseurl: /Semester6 # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
